In [1]:
import pandas as pd

In [2]:
data = pd.read_csv("employee_data.csv")

In [3]:
data

# 4 function : apply() , map() , replace()

   ID     Name  Age Department  Salary
0   1    Alice   25         HR   55000
1   2      Bob   32         IT   72000
2   3  Charlie   28    Finance   48000
3   4    David   45  Marketing   91000
4   5      Eva   38         IT   65000
5   6    Frank   29    Finance   50000
6   7    Grace   41         HR   82000
7   8   Hannah   26  Marketing   47000
8   9      Ian   35         IT   75000
9  10    Julia   30    Finance   60000

In [10]:
d = data.copy()

# def logic():
#     if d["Salary"] < 50000:
#         return "20%"
#     else:
#         return "10%"
    
# apply
d["tax"] = d["Salary"].apply(lambda x : "20%" if x > 50000 else "10%")
d



# map

dep_map = {"HR":"Faltu" , "IT" : "ITI wala"}
d["Department"] = d["Department"].map(dep_map)
d

#  replace function


d["Department"] = d["Department"].replace("ITI wala" , "Nhi pata")
d

   ID     Name  Age Department  Salary  tax
0   1    Alice   25      Faltu   55000  20%
1   2      Bob   32   Nhi pata   72000  20%
2   3  Charlie   28        NaN   48000  10%
3   4    David   45        NaN   91000  20%
4   5      Eva   38   Nhi pata   65000  20%
5   6    Frank   29        NaN   50000  10%
6   7    Grace   41      Faltu   82000  20%
7   8   Hannah   26        NaN   47000  10%
8   9      Ian   35   Nhi pata   75000  20%
9  10    Julia   30        NaN   60000  20%