In [1]:
# groupby : divide on specific groups
# min() , max() , mean() ---> aggregate fucntions agg()

In [3]:
import pandas as pd 
data = pd.read_csv("raw_data.csv")
data

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
1    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith   NaN  Canada   Female  62000.0
3    3          Alex   NaN     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female      NaN
5    5        Li Wei  27.0   China     Male  51000.0
6    6           NaN  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0     NaN     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz   NaN  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA      NaN  58000.0

In [6]:
# group by
data.groupby("gender")["income"].mean()
data.groupby("gender")["income"].min()
data.groupby("gender")["income"].max()

gender
Female     73000.0
Male       68000.0
Unknown    47000.0
Name: income, dtype: float64

In [9]:
# all min , max in one place

data.groupby("gender")["income"].agg(["mean" , "min" , "max"])
# data.groupby("gender")["income"].aggregate(["mean" , "min" , "max"])

                 mean      min      max
gender
Female   65666.666667  62000.0  73000.0
Male     54800.000000  45000.0  68000.0
Unknown  47000.000000  47000.0  47000.0

In [10]:
# now not only one parameter "income" , we want to calculate various value mean, min , max, etc

data.groupby("gender").agg({
  "income" : "mean" , 
    "age" : "min"
})

               income   age
gender
Female   65666.666667  29.0
Male     54800.000000  27.0
Unknown  47000.000000   NaN

In [12]:
# add custom labels to newly cretated columns of mean adn avg
data.groupby("country").agg(
  AvgIncome=("income" ,"mean" ), 
    MinAge=("age" , "min")
)

         AvgIncome  MinAge
country
Canada     62000.0     NaN
China      51000.0    27.0
India      73000.0    45.0
Mexico     45000.0     NaN
Spain          NaN    34.0
USA        55400.0    29.0