In [1]:
import pandas as pd

In [3]:
data = pd.read_csv("raw_data.csv")

data

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
1    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith   NaN  Canada   Female  62000.0
3    3          Alex   NaN     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female      NaN
5    5        Li Wei  27.0   China     Male  51000.0
6    6           NaN  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0     NaN     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz   NaN  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA      NaN  58000.0

In [6]:
# identify missing value : isnull() or isna()
data.isnull() # TRUE value are missing

       id   name    age  country  gender  income
0   False  False  False    False   False   False
1   False  False  False    False   False   False
2   False  False   True    False   False   False
3   False  False   True    False   False   False
4   False  False  False    False   False    True
5   False  False  False    False   False   False
6   False   True  False    False   False   False
7   False  False  False     True   False   False
8   False  False  False    False   False   False
9   False  False   True    False   False   False
10  False  False  False    False    True   False

In [8]:
# count total missing value in all table
data.isna().sum()

id         0
name       1
age        3
country    1
gender     1
income     1
dtype: int64

In [10]:
# removing from tables
data.dropna() # display row without missing value

   id        name   age country  gender   income
0   1    John Doe  29.0     USA    Male  55000.0
1   1    John Doe  29.0     USA    Male  55000.0
5   5      Li Wei  27.0   China    Male  51000.0
8   8  Rachel Lee  29.0     USA  Female  62000.0

In [13]:
#  fill null value with other value
avgAge = data["age"].mean()
data.fillna(avgAge)

    id          name    age country   gender    income
0    1      John Doe  29.00     USA     Male  55000.00
1    1      John Doe  29.00     USA     Male  55000.00
2    2    Jane Smith  32.75  Canada   Female  62000.00
3    3          Alex  32.75     USA  Unknown  47000.00
4    4  Maria Garcia  34.00   Spain   Female     32.75
5    5        Li Wei  27.00   China     Male  51000.00
6    6         32.75  45.00   India   Female  73000.00
7    7    Ahmed Khan  38.00   32.75     Male  68000.00
8    8    Rachel Lee  29.00     USA   Female  62000.00
9    9   Carlos Ruiz  32.75  Mexico     Male  45000.00
10  10   Emily Davis  31.00     USA    32.75  58000.00

In [15]:
# forward and backward filling

data.ffill() # upper copy to lower
data.bfill() # lower copy to upper

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
1    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith  34.0  Canada   Female  62000.0
3    3          Alex  34.0     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female  51000.0
5    5        Li Wei  27.0   China     Male  51000.0
6    6    Ahmed Khan  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0     USA     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz  31.0  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA      NaN  58000.0

In [23]:
# ################ Handling Duplicates #################################
# duplicated()

data.duplicated()
data["country"].duplicated()

# drop_duplicated()
orgcopy = data.copy() # contain duplicate

data.drop_duplicates() # chnage in copy
data.drop_duplicates(inplace=True) # chnage in real data

data # see original get inplaced.

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith   NaN  Canada   Female  62000.0
3    3          Alex   NaN     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female      NaN
5    5        Li Wei  27.0   China     Male  51000.0
6    6           NaN  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0     NaN     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz   NaN  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA      NaN  58000.0

In [26]:
#  to_datetime() is used to change your data str to date type
date = pd.to_datetime("2026-12-12")
# date = "2026-12-12"
type(date)

pandas._libs.tslibs.timestamps.Timestamp

In [28]:

# Handles String value in data


data["gender"].str.lower()


# data["gender"].str.upper()
# data["gender"].str.capitalize() >>>> only first letter capital

# str.strip() >>>>> remove spaces

str.split("")

# str.contains(val, case=False)

0        male
2      female
3     unknown
4      female
5        male
6      female
7        male
8      female
9        male
10        NaN
Name: gender, dtype: object